/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'

const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/connections': typeof ConnectionsRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/threads': typeof ThreadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/connections': typeof ConnectionsRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/threads': typeof ThreadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/connections': typeof ConnectionsRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/outreach': typeof OutreachRoute
  '/settings': typeof SettingsRoute
  '/threads': typeof ThreadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/connections'
    | '/contacts'
    | '/documents'
    | '/markets'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/threads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/connections'
    | '/contacts'
    | '/documents'
    | '/markets'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/threads'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/connections'
    | '/contacts'
    | '/documents'
    | '/markets'
    | '/opportunities'
    | '/outreach'
    | '/settings'
    | '/threads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  ConnectionsRoute: typeof ConnectionsRoute
  ContactsRoute: typeof ContactsRoute
  DocumentsRoute: typeof DocumentsRoute
  MarketsRoute: typeof MarketsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  OutreachRoute: typeof OutreachRoute
  SettingsRoute: typeof SettingsRoute
  ThreadsRoute: typeof ThreadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  ConnectionsRoute: ConnectionsRoute,
  ContactsRoute: ContactsRoute,
  DocumentsRoute: DocumentsRoute,
  MarketsRoute: MarketsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  OutreachRoute: OutreachRoute,
  SettingsRoute: SettingsRoute,
  ThreadsRoute: ThreadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
